#!/bin/sh

test -f Makefile && {
	echo "Makefile exists, owerwrite? [y/n]"
	read ans
	if test "$ans" != "y" ; then exit ; fi
}

for m in `find -mindepth 2 -name Makefile` ; do
	echo include $m
done > Makefile
