#!/bin/sh

die() { echo $@ >&2 ; exit 1; }

IMG=$1
test -z "$IMG" && die "usage: $0 IMAGE.ELF"

LV=`sh ./tools/setlocalversion`
BR=`git branch | grep \* | awk '{print $2}'`

test -z "$LV" && die "Unable to determine version"
test -z "$BR" && die "Unable to determine branch name"

if echo $LV | grep -q dirty ; then
	git status | head
	echo -n "Sure to snapshot dirty state [y/n]? "
	read ans
	test "$ans" = "y" || die "Commit first."
fi

GDIR="$HOME/proj/mboot-bin"
test -d "$GDIR" || die "$GDIR doesn't exist"
WDIR=`mktemp -d`
ADIR="$WDIR/$IMG-$BR$LV"
mkdir "$ADIR" || die "Unable to mkdir $ADIR"
cp $IMG $ADIR/ &&
cp $IMG.bin $ADIR/ &&
{ if test -f $IMG.img ; then cp $IMG.img $ADIR/ ; else true ; fi } &&
cp rungdb $ADIR/ &&
{ cd $WDIR && tar -zcvpf `basename $ADIR`.tar.gz `basename $ADIR` ; } &&
cp $ADIR.tar.gz $GDIR && {
	cd $GDIR &&
	git add `basename $ADIR`.tar.gz
	git commit -m "`basename $ADIR`.tar.gz"
	git push public master
}

