COBJS-$(CONFIG_ADDR_MAP) += lib/addr_map.o
COBJS-$(CONFIG_BZIP2) += lib/bzlib.o
COBJS-$(CONFIG_BZIP2) += lib/bzlib_crctable.o
COBJS-$(CONFIG_BZIP2) += lib/bzlib_decompress.o
COBJS-$(CONFIG_BZIP2) += lib/bzlib_randtable.o
COBJS-$(CONFIG_BZIP2) += lib/bzlib_huffman.o
COBJS-$(CONFIG_USB_TTY) += lib/circbuf.o
COBJS-y += lib/part_dos.o
COBJS-y += lib/crc16.o
COBJS-y += lib/crc32.o
COBJS-y += lib/ctype.o
COBJS-y += lib/display_options.o
COBJS-y += lib/div64.o
COBJS-y += lib/errno.o
COBJS-$(CONFIG_GZIP) += lib/gunzip.o
COBJS-y += lib/hashtable.o
COBJS-$(CONFIG_LMB) += lib/lmb.o
COBJS-y += lib/ldiv.o
COBJS-$(CONFIG_MD5) += lib/md5.o
COBJS-y += lib/net_utils.o
COBJS-y += lib/qsort.o
COBJS-$(CONFIG_SHA1) += lib/sha1.o
COBJS-$(CONFIG_SHA256) += lib/sha256.o
COBJS-y += lib/string.o
COBJS-y	+= lib/strmhz.o
COBJS-y += lib/time.o
COBJS-y += lib/vsprintf.o
COBJS-$(CONFIG_ZLIB) += lib/zlib.o
COBJS-$(CONFIG_RBTREE)	+= lib/rbtree.o

include lib/lzo/Makefile
include lib/lzma/Makefile
include lib/libfdt/Makefile

